name = "evoting-sman1-bantarujeg"
compatibility_date = "2024-01-01"

# Pages configuration
pages_build_output_dir = ".next"

# Build configuration
[build]
command = "npm run build"

# D1 Database binding for Pages
[[d1_databases]]
binding = "DB"
database_name = "evoting-db"
database_id = "1e454747-b814-4645-b3b4-cfc4af430585"

# Production environment
[env.production]
name = "evoting-sman1-bantarujeg-production"

[[env.production.d1_databases]]
binding = "DB"
database_name = "evoting-db-production"
database_id = "9b6fa9d1-f548-4073-9ee8-b58fdf306552"
